-- =====================================================
-- SUPABASE STORAGE HARDENING
-- =====================================================
-- Run this in Supabase SQL Editor after deploying the app update.
-- New door uploads now use this path:
--   door-images/{auth.uid()}/{filename}
--
-- Existing legacy files under:
--   door-images/doors/{filename}
-- remain readable, but new user uploads must go to their own folder.
-- =====================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin',
    false
  );
$$;

-- Remove broad or legacy policy names if they exist.
DROP POLICY IF EXISTS "Public read access" ON storage.objects;
DROP POLICY IF EXISTS "Public read access to door images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload door images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own door images" ON storage.objects;
DROP POLICY IF EXISTS "Users can upload own door images" ON storage.objects;
DROP POLICY IF EXISTS "Users can update own door images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own door images" ON storage.objects;
DROP POLICY IF EXISTS "Admins can upload to door-images" ON storage.objects;
DROP POLICY IF EXISTS "Admins can update door-images" ON storage.objects;
DROP POLICY IF EXISTS "Admins can delete from door-images" ON storage.objects;

-- Public read is expected because door images are displayed publicly in the app.
CREATE POLICY "Public read access to door images"
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'door-images');

-- Authenticated users can only upload into their own user-id folder.
CREATE POLICY "Users can upload own door images"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'door-images'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Authenticated users can only update files in their own user-id folder.
CREATE POLICY "Users can update own door images"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'door-images'
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'door-images'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Authenticated users can only delete files in their own user-id folder.
CREATE POLICY "Users can delete own door images"
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'door-images'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Admins can manage every door image.
CREATE POLICY "Admins can upload to door-images"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'door-images'
  AND public.is_admin()
);

CREATE POLICY "Admins can update door-images"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'door-images'
  AND public.is_admin()
)
WITH CHECK (
  bucket_id = 'door-images'
  AND public.is_admin()
);

CREATE POLICY "Admins can delete from door-images"
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'door-images'
  AND public.is_admin()
);

-- Marketing assets are generated by backend/n8n flows and can be displayed publicly.
DROP POLICY IF EXISTS "Public read access to marketing assets" ON storage.objects;

CREATE POLICY "Public read access to marketing assets"
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'marketing-assets');

-- Verification:
-- SELECT policyname, cmd, roles, qual, with_check
-- FROM pg_policies
-- WHERE schemaname = 'storage' AND tablename = 'objects'
-- ORDER BY policyname;
